keys:
  - &user_derek       age1m9lkn3stwwkgdrrhvt2npqs6hhvpceduwz4csrzgwlypde4jd3usphxwca
  - &user_derek_yk    age1yubikey1qtsz0xkjqqxvm4uev2d6fpkdvu5zmx9v8th8dfzpdtcx23qedk832f7nf8v
  - &host_littlecreek age1lttery3xgzrze6757s8mmg48slu27jwhawjhn98tyx0ft2fekd3qyuhmy0
creation_rules:
  - path_regex: hosts/littlecreek/secrets\.yaml$
    key_groups:
    - age:
      - *user_derek
      - *host_littlecreek
